name: Update Coverage

on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    name: Update coverage badge
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.19

      - name: Caching
        uses: actions/cache@v3
        with:
          path: ${{ runner.workspace }}/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles("**/go.sum") }}

      - name: Run Go Test
        run: |
          go test -v ./... -covermode=count -coverprofile=coverage.out
          go tool cover -func=coverage.out -o=coverage.out

      - name: Go Coverage Badge
        uses: tj-actions/coverage-badge-go@v2
        with:
          filename: coverage.out
          text: coverage

      - name: Verify Changed files
        uses: tj-actions/verify-changed-files@v16
        id: verify-changed-files
        with:
          files: README.md

      - name: Commit and Push changes
        if: steps.verify-changed-files.outputs.files_changed == "true"
        uses: endbug/add-and-commit@v7
        with:
          author_name: "GitHub Action"
          author_email: "action@github.com"
          message: "chore: badge de coverage atualizado"
          push: true
